---
abstract: 'Include the Mojo library in you application!'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101310'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Command-Package
recommends: {}
requires:
  Cwd: 0
  File::Copy: 0
  File::Find: 0
  Mojo: 0
  Mojolicious: 0
version: 0.01
